FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.23-openshift-4.19 AS builder
WORKDIR /go/src/k8s.io/autoscaler
COPY . .
WORKDIR /go/src/k8s.io/autoscaler/cluster-autoscaler
RUN go build --tags clusterapi -o ./cluster-autoscaler .

FROM registry.ci.openshift.org/ocp/4.19:base-rhel9
COPY --from=builder /go/src/k8s.io/autoscaler/cluster-autoscaler/cluster-autoscaler /usr/bin/
CMD /usr/bin/cluster-autoscaler
LABEL summary="Cluster Autoscaler for OpenShift and Kubernetes"
