FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.16 AS builder
WORKDIR /go/src/k8s.io/autoscaler/vertical-pod-autoscaler
COPY . .
RUN go build ./pkg/admission-controller
RUN go build ./pkg/updater
RUN go build ./pkg/recommender

FROM registry.ci.openshift.org/ocp/4.16:base-rhel9
COPY --from=builder \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/admission-controller \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/updater \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/recommender \
    /usr/bin/
LABEL summary="Vertical Pod Autoscaler for OpenShift and Kubernetes"
