FROM registry.ci.openshift.org/openshift/release:golang-1.15 AS builder
WORKDIR /go/src/k8s.io/autoscaler/vertical-pod-autoscaler
COPY . .
RUN go build ./pkg/admission-controller
RUN go build ./pkg/updater
RUN go build ./pkg/recommender

FROM registry.ci.openshift.org/openshift/origin-v4.0:base
COPY --from=builder \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/admission-controller \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/updater \
    /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/recommender \
    /usr/bin/
LABEL summary="Vertical Pod Autoscaler for OpenShift and Kubernetes"
